// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/proto/manager.proto

/*
Package server is a generated protocol buffer package.

It is generated from these files:
	server/proto/manager.proto

It has these top-level messages:
	RestoreVolumeRequest
	EntriesList
	Entry
	Empty
	ScheduleSavingRequest
	SaveVolumeRequest
*/
package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RestoreVolumeRequest struct {
	VolumeName string `protobuf:"bytes,1,opt,name=volumeName" json:"volumeName,omitempty"`
}

func (m *RestoreVolumeRequest) Reset()                    { *m = RestoreVolumeRequest{} }
func (m *RestoreVolumeRequest) String() string            { return proto.CompactTextString(m) }
func (*RestoreVolumeRequest) ProtoMessage()               {}
func (*RestoreVolumeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RestoreVolumeRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

type EntriesList struct {
	Entries []*Entry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
}

func (m *EntriesList) Reset()                    { *m = EntriesList{} }
func (m *EntriesList) String() string            { return proto.CompactTextString(m) }
func (*EntriesList) ProtoMessage()               {}
func (*EntriesList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EntriesList) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type Entry struct {
	Volume string `protobuf:"bytes,1,opt,name=volume" json:"volume,omitempty"`
	Cron   string `protobuf:"bytes,2,opt,name=cron" json:"cron,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Entry) GetVolume() string {
	if m != nil {
		return m.Volume
	}
	return ""
}

func (m *Entry) GetCron() string {
	if m != nil {
		return m.Cron
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ScheduleSavingRequest struct {
	Schedule string             `protobuf:"bytes,1,opt,name=schedule" json:"schedule,omitempty"`
	Volume   *SaveVolumeRequest `protobuf:"bytes,2,opt,name=volume" json:"volume,omitempty"`
}

func (m *ScheduleSavingRequest) Reset()                    { *m = ScheduleSavingRequest{} }
func (m *ScheduleSavingRequest) String() string            { return proto.CompactTextString(m) }
func (*ScheduleSavingRequest) ProtoMessage()               {}
func (*ScheduleSavingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ScheduleSavingRequest) GetSchedule() string {
	if m != nil {
		return m.Schedule
	}
	return ""
}

func (m *ScheduleSavingRequest) GetVolume() *SaveVolumeRequest {
	if m != nil {
		return m.Volume
	}
	return nil
}

type SaveVolumeRequest struct {
	VolumeName  string `protobuf:"bytes,1,opt,name=volumeName" json:"volumeName,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination" json:"destination,omitempty"`
}

func (m *SaveVolumeRequest) Reset()                    { *m = SaveVolumeRequest{} }
func (m *SaveVolumeRequest) String() string            { return proto.CompactTextString(m) }
func (*SaveVolumeRequest) ProtoMessage()               {}
func (*SaveVolumeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SaveVolumeRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

func (m *SaveVolumeRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func init() {
	proto.RegisterType((*RestoreVolumeRequest)(nil), "server.RestoreVolumeRequest")
	proto.RegisterType((*EntriesList)(nil), "server.EntriesList")
	proto.RegisterType((*Entry)(nil), "server.Entry")
	proto.RegisterType((*Empty)(nil), "server.Empty")
	proto.RegisterType((*ScheduleSavingRequest)(nil), "server.ScheduleSavingRequest")
	proto.RegisterType((*SaveVolumeRequest)(nil), "server.SaveVolumeRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Manager service

type ManagerClient interface {
	SaveVolume(ctx context.Context, in *SaveVolumeRequest, opts ...grpc.CallOption) (*Empty, error)
	ScheduleSaving(ctx context.Context, in *ScheduleSavingRequest, opts ...grpc.CallOption) (*Empty, error)
	ListEntries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EntriesList, error)
	Restore(ctx context.Context, in *RestoreVolumeRequest, opts ...grpc.CallOption) (*Empty, error)
}

type managerClient struct {
	cc *grpc.ClientConn
}

func NewManagerClient(cc *grpc.ClientConn) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) SaveVolume(ctx context.Context, in *SaveVolumeRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/server.Manager/SaveVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) ScheduleSaving(ctx context.Context, in *ScheduleSavingRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/server.Manager/ScheduleSaving", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) ListEntries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EntriesList, error) {
	out := new(EntriesList)
	err := grpc.Invoke(ctx, "/server.Manager/ListEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) Restore(ctx context.Context, in *RestoreVolumeRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/server.Manager/Restore", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Manager service

type ManagerServer interface {
	SaveVolume(context.Context, *SaveVolumeRequest) (*Empty, error)
	ScheduleSaving(context.Context, *ScheduleSavingRequest) (*Empty, error)
	ListEntries(context.Context, *Empty) (*EntriesList, error)
	Restore(context.Context, *RestoreVolumeRequest) (*Empty, error)
}

func RegisterManagerServer(s *grpc.Server, srv ManagerServer) {
	s.RegisterService(&_Manager_serviceDesc, srv)
}

func _Manager_SaveVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).SaveVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Manager/SaveVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).SaveVolume(ctx, req.(*SaveVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_ScheduleSaving_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleSavingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).ScheduleSaving(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Manager/ScheduleSaving",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).ScheduleSaving(ctx, req.(*ScheduleSavingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_ListEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).ListEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Manager/ListEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).ListEntries(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Manager/Restore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Restore(ctx, req.(*RestoreVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Manager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveVolume",
			Handler:    _Manager_SaveVolume_Handler,
		},
		{
			MethodName: "ScheduleSaving",
			Handler:    _Manager_ScheduleSaving_Handler,
		},
		{
			MethodName: "ListEntries",
			Handler:    _Manager_ListEntries_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _Manager_Restore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/proto/manager.proto",
}

func init() { proto.RegisterFile("server/proto/manager.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4f, 0x83, 0x40,
	0x10, 0x2d, 0x6a, 0x8b, 0x0e, 0xd1, 0xc4, 0xf1, 0x23, 0x95, 0xa8, 0x69, 0xf6, 0x62, 0x4f, 0x6d,
	0x2c, 0x49, 0xd3, 0xa3, 0x97, 0xde, 0xd4, 0x03, 0x44, 0xef, 0x6b, 0x3b, 0x56, 0x92, 0x02, 0x75,
	0x77, 0x21, 0xe9, 0xff, 0xf6, 0x07, 0x18, 0x96, 0x85, 0x42, 0xa8, 0xf1, 0xc6, 0xbc, 0xb7, 0xbc,
	0x99, 0x79, 0x6f, 0xc0, 0x95, 0x24, 0x32, 0x12, 0xe3, 0x8d, 0x48, 0x54, 0x32, 0x8e, 0x78, 0xcc,
	0x57, 0x24, 0x46, 0xba, 0xc2, 0x5e, 0xc1, 0xb1, 0x29, 0x5c, 0xfa, 0x24, 0x55, 0x22, 0xe8, 0x3d,
	0x59, 0xa7, 0x11, 0xf9, 0xf4, 0x9d, 0x92, 0x54, 0x78, 0x0f, 0x90, 0x69, 0xe0, 0x95, 0x47, 0xd4,
	0xb7, 0x06, 0xd6, 0xf0, 0xc4, 0xaf, 0x21, 0x6c, 0x0a, 0xce, 0x3c, 0x56, 0x22, 0x24, 0xf9, 0x1c,
	0x4a, 0x85, 0x0f, 0x60, 0x53, 0x51, 0xf6, 0xad, 0xc1, 0xe1, 0xd0, 0x99, 0x9c, 0x8e, 0x8a, 0x06,
	0xa3, 0xfc, 0xd5, 0xd6, 0x2f, 0x59, 0xe6, 0x41, 0x57, 0x23, 0x78, 0x0d, 0xbd, 0x42, 0xce, 0x88,
	0x9b, 0x0a, 0x11, 0x8e, 0x16, 0x22, 0x89, 0xfb, 0x07, 0x1a, 0xd5, 0xdf, 0xcc, 0x86, 0xee, 0x3c,
	0xda, 0xa8, 0x2d, 0xfb, 0x84, 0xab, 0x60, 0xf1, 0x45, 0xcb, 0x74, 0x4d, 0x01, 0xcf, 0xc2, 0x78,
	0x55, 0x8e, 0xeb, 0xc2, 0xb1, 0x34, 0x84, 0xd1, 0xab, 0x6a, 0x7c, 0xac, 0x3a, 0xe5, 0x9a, 0xce,
	0xe4, 0xa6, 0x1c, 0x2d, 0xe0, 0x59, 0x73, 0xeb, 0x72, 0x08, 0xf6, 0x06, 0xe7, 0x2d, 0xf2, 0x3f,
	0x4b, 0x70, 0x00, 0xce, 0x92, 0xa4, 0x0a, 0x63, 0xae, 0xc2, 0x6a, 0x81, 0x3a, 0x34, 0xf9, 0xb1,
	0xc0, 0x7e, 0x29, 0x62, 0xc0, 0x19, 0xc0, 0xae, 0x05, 0xfe, 0x3d, 0x93, 0xbb, 0x73, 0x52, 0x5b,
	0xd0, 0xc1, 0x27, 0x38, 0x6b, 0x9a, 0x80, 0x77, 0xd5, 0xdf, 0xfb, 0xcc, 0x69, 0x2b, 0x78, 0xe0,
	0xe4, 0xa9, 0x99, 0x00, 0xb1, 0xc9, 0xbb, 0x17, 0xf5, 0xe8, 0x4c, 0xc0, 0xac, 0x83, 0x33, 0xb0,
	0xcd, 0xa5, 0xe0, 0x6d, 0xf9, 0x62, 0xdf, 0xe9, 0xb4, 0xda, 0x7d, 0xf4, 0xf4, 0xc9, 0x79, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x26, 0x85, 0xa0, 0x90, 0x02, 0x00, 0x00,
}
